"use client";
import "./globals.css";
import Header from "@components/common/header/header";
import axios from "axios";
import Modal from "react-modal";

axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_URL;

Modal.setAppElement("#container");

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {
  return (
    <div id="container">
      <Header />
      <Component {...pageProps} />
    </div>
  );
}
